In [1]:
path_file = '/home/ml/BI_Help/data/raw/Import/corresp_Labels/MATKL T023T ALL AQ6_m_1.csv'
path_file_fr ='/home/ml/BI_Help/data/processed/codes_labels_fr.pkl'
path_code_corrige = '/home/ml/BI_Help/data/processed/codes_corrige.pkl'
path_file_fr_cleaned = '/home/ml/BI_Help/data/processed/codes_labels_fr_cleaned.pkl'
path_code_to_remove = '/home/ml/BI_Help/data/processed/code_to_remove.pkl'

In [2]:
import pandas as pd
import re

In [3]:
pattern_1 = re.compile('ne plus|pas utiliser', re.IGNORECASE)
pattern_2 = re.compile('utiliser', re.IGNORECASE)

In [4]:
df = pd.read_csv(path_file, sep='|', encoding='ISO-8859-15')

In [5]:
df['Language'] = df['Language'].str.strip()

In [6]:
df_fr = df[df['Language'] == 'FR']

In [7]:
df_fr.dropna(inplace=True)

/home/ml/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [8]:
df_fr['Matl Group'] = df_fr['Matl Group'].str.strip()

/home/ml/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [9]:
df_fr.to_pickle(path_file_fr)

In [10]:
df_read = pd.read_pickle(path_file_fr)

In [12]:
df_remove_code = df_read[df_read['Material grp desc. 2'].str.contains(pat = pattern_1, regex=True )]

In [13]:
df_remove_code.to_pickle(path_code_to_remove)

In [14]:
df_remove_code

,Language,Matl Group,Material Group Desc.,Material grp desc. 2
1111,FR,025003,Ne plus Utiliser,Ne plus Utiliser ...
1114,FR,025006,Ne plus Utiliser,Ne plus Utiliser ...
1143,FR,05123,Ne plus utiliser,Ne plus utiliser ...
1195,FR,09100B,Ne pas Utiliser,Ne pas Utiliser ...
1216,FR,15220,Ne pas Utiliser,Ne pas Utiliser ...
1217,FR,15220A,Ne pas Utiliser,Ne pas Utiliser ...
1276,FR,19510,Ne pas Utiliser,Ne pas Utiliser ...
1300,FR,25001,Ne pas Utiliser,Ne pas Utiliser ...
1301,FR,25002,Ne pas Utiliser,Ne pas Utiliser ...
1302,FR,25003,Ne pas Utiliser,Ne pas Utiliser ...
1303,FR,25004,Ne pas Utiliser,Ne pas Utiliser ...
1304,FR,25005,Ne pas Utiliser,Ne pas Utiliser ...
1305,FR,25006,Ne pas Utiliser,Ne pas Utiliser ...
1306,FR,255,Ne pas Utiliser,Ne pas Utiliser ...
1342,FR,34000,Ne pas Utiliser,Ne pas Utiliser ...
1395,FR,38500,ne plus utiliser,ne plus utiliser ...
1397,FR,38700,ne plus utiliser,ne plus utiliser ...
1398,FR,38701,ne plus utiliser,ne plus utiliser ...
1399,FR,38702,ne plus utiliser,ne plus utiliser ...
1401,FR,38801,ne plus utiliser,ne plus utiliser ...
1402,FR,38802,ne plus utiliser,ne plus utiliser ...
1403,FR,38900,ne plus utiliser,ne plus utiliser ...
1404,FR,38901,ne plus utiliser,ne plus utiliser ...
1405,FR,38902,ne plus utiliser,ne plus utiliser ...
1451,FR,47500REP,NE PLUS UTILISER,NE PLUS UTILISER ...
1504,FR,59300,utiliser 57300,ne plus utiliser ...
1526,FR,61500,ne plus utiliser,ne plus utiliser ...
1555,FR,67400,ne plus utiliser,ne plus utiliser ...
1556,FR,67500,ne plus utiliser,ne plus utiliser ...
1581,FR,79900,utiliser 75100,ne plus utiliser ...
1624,FR,89100,ne plus utiliser,ne plus utiliser ...
1633,FR,89400,utiliser 89300,ne plus utiliser ...
1636,FR,91100,Ne plus utiliser,Ne plus utiliser ...
1640,FR,91200A,Ne plus utiliser,ne plus utiliser ...
1641,FR,91200B,Ne plus utiliser,ne plus utiliser ...
1663,FR,92611,Ne plus utiliser,Ne pas utiliser ...
1679,FR,9800A,Ne plus utiliser,Ne plus utiliser ...

In [15]:
df_read = df_read[~df_read['Material grp desc. 2'].str.contains(pat=pattern_1, regex=True )]

In [16]:
df_read.to_pickle(path_file_fr_cleaned)

In [17]:
df_list_to_remove = list(df_remove_code['Matl Group'])

In [18]:
df_read = df_read[~df_read['Matl Group'].isin(df_list_to_remove)]

In [19]:
df_read.sample(20)

,Language,Matl Group,Material Group Desc.,Material grp desc. 2
1292,FR,22200,utiliser 42300,utiliser 42300 ...
1648,FR,92101,utiliser 92000,utiliser 92000 ...
1222,FR,16000CIR,STDevSpecAT CIR,ST Dev logiciels tech sur spécif en assist tec...
1294,FR,22500,utiliser 42300,utiliser 42300 ...
1653,FR,92222,utiliser 92000,utiliser 92000 ...
1127,FR,032002,Electricité,Electricité ...
1444,FR,47100,ETUDE/PROTO ELECT.,Etude et Dev Electronique en AT (yc maquettes ...
1426,FR,42540,AUTRE COMPOSANT MECA,"Maint. Comp. Méca. (moteur, actionneur, vérin,..."
1593,FR,81411,utiliser 81300,utiliser 81300 ...
1178,FR,071002,Frais de récept Voya,Frais de réception liés aux voyages ...
1455,FR,48500,CONCEPTION RACK&BAIE,Etude et Dev Racks/Baies en AT (yc maquettes e...
1429,FR,43200,utiliser 44100,utiliser 44100 ...
1418,FR,41400,ELECTROMECA ASSEMB.,ST Assemblages Électromécaniques (Thales Desig...
1609,FR,86102,utiliser 42500,utiliser 42500 ...
1549,FR,65800,utiliser 35100,utiliser 35100 ...
1514,FR,60700,PREST. BE MECA&ELECT,Prest en AT de B.Etude mécanique/électrique/él...
1561,FR,71100,utiliser 42500,utiliser 42500 ...
1668,FR,92802,utiliser 92002,utiliser 92002 ...
1298,FR,22900,utiliser 42300,utiliser 42300 ...
1463,FR,52500,RESONATEURS,résonateurs ...

In [20]:
def df_code_correction():
    df = pd.read_pickle(path_file_fr_cleaned)
    df = df[df['Material grp desc. 2'].str.contains(pat = pattern_2, regex=True)]
    df['code_correction'] = df['Material grp desc. 2'].apply(lambda x: pattern_2.sub('', x))
    df['code_correction'] = df['code_correction'].str.strip()
    return df

In [21]:
df_code_corrige = df_code_correction()

In [22]:
df_code_corrige.drop_duplicates(inplace=True)

In [23]:
df_code_corrige[['Matl Group', 'code_correction']].to_pickle(path_code_corrige)

In [24]:
df = pd.read_pickle(path_code_corrige)

In [25]:
df

     Matl Group code_correction
1092      01000           01200
1098     015000           02800
1099     015001           02800
1109     025001          02300A
1110     025002          02300B
...         ...             ...
1669      92822           92022
1675      95200           36100
1677      96100           95000
1678      97100           95000
1681      98200           98100

[240 rows x 2 columns]

In [26]:
df['code_correction'].unique()

array(['01200', '02800', '02300A', '02300B', '02300C', '02300D', '05200',
       '03200', '06700', '15201', '071002', '89300', '09100', '05700',
       '04200', '70600', '15201/01A', '16000', '14600', '15200', '47100',
       '41200', '47500', '30000', '41300', '41500', '40500', '42700',
       '43400', '43500', '47200', '42300', '44100', '31700', '33000',
       '33100', '34500', '33200', '33201', '33240', '33202', '34400',
       '34440REP', '34700', '34701', '34740', '20200', '41100', '39100',
       '36100', '30800', '52500', '54100', '66600', '56100', '57300',
       '57600', '57100', '62400', '71400', '41400', '66100', '35100',
       '42500', '40100', '35200', '35500', '81300', '30400', '37200',
       '88000', '07000', '92000', '92001', '92002', '92022', '95000',
       '98100'], dtype=object)