In [1]:
import spacy
from nltk.corpus import wordnet as wn

nlp = spacy.load("fr_core_news_sm")

In [14]:
[synset.lemma_names('fra') for synset in wn.synsets('entreprise', lang='fra')]

[['entreprise', 'projet'],
 ['effort', 'entreprise', 'tentative'],
 ['entreprise'],
 ['entreprise'],
 ['entreprise'],
 ['entreprise', 'initiative'],
 ['bow-window', 'corporation', 'entreprise', 'oriel', 'société', 'ventre'],
 ['entreprise'],
 ['entreprise'],
 ['compagnie', 'entreprise', 'société'],
 ['corporation', 'entreprise', 'société'],
 ['entreprise', 'firme'],
 ['entreprise']]

In [13]:
[synset.lemma_names('fra') for synset in wn.synsets('vice', lang='fra')]

[['vice'],
 ['étau', 'vice', 'vice-président'],
 ['défaut', 'dégât', 'faille', 'lacune', 'préjudice', 'vice'],
 ['défaut', 'dégât', 'faille', 'préjudice', 'vice']]

In [4]:
PathText = "/home/ml/BI_Help/data/raw/Fusion_Procurement_BI/"
PathCodeCorrige = '/home/ml/BI_Help/data/processed/codes_corrige.pkl'
PathAVSCorrection = '/home/ml/BI_Help/data/processed/codes_labels.pkl'
PathJson = "/home/ml/BI_Help/data/processed/outputfile.json"

In [5]:
import pandas as pd

In [6]:
df_code_corrige = pd.read_pickle(PathCodeCorrige)

In [7]:
df_code_corrige.sample(20)

     Matl Group                                    code_correction
1531      62600   62400                                        ...
1233      16900   15200                                        ...
1258      17320   41200                                        ...
1338      33140   33240                                        ...
1629      89202   89300                                        ...
1580      79800   35500                                        ...
1563      71300   42500                                        ...
1154     067002   06700                                        ...
1651      92201   92000                                        ...
1468      53600   66600                                        ...
1494      57800   66600                                        ...
1261      18000   30000                                        ...
1562      71200   42500                                        ...
1307      25500   44100                                        ...
1421      41700   41100                                        ...
1292      22200   42300                                        ...
1348      34440   34440REP                                     ...
1479      55600   54100                                        ...
1428      43100   44100                                        ...
1323      31010   33000                                        ...

In [8]:
df_code_corrige.shape

(240, 2)

In [103]:
df_code_corrige.dropna(inplace=True)

In [109]:
df_code_corrige[df_code_corrige['code_correction'].str.contains('53000')]

Empty DataFrame
Columns: [Matl Group, code_correction]
Index: []

In [104]:
df_code_corrige.shape

(257, 2)

In [75]:
df_PathAVSCorrection = pd.read_pickle(PathAVSCorrection)

In [105]:
df_PathAVSCorrection.shape

(586, 4)

In [101]:
df_PathAVSCorrection[df_PathAVSCorrection['Matl Group'].str.contains('53000')]

Empty DataFrame
Columns: [Language, Matl Group, Material Group Desc., Material grp desc. 2]
Index: []

In [106]:
df_PathAVSCorrection.dropna(inplace=True)

In [107]:
df_PathAVSCorrection.shape

(586, 4)